// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// rpexp
NumericVector rpexp(const int n, NumericVector t, NumericVector rate, NumericVector t0);
RcppExport SEXP purged_rpexp(SEXP nSEXP, SEXP tSEXP, SEXP rateSEXP, SEXP t0SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const int >::type n(nSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rate(rateSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP );
        NumericVector __result = rpexp(n, t, rate, t0);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
